#!/bin/bash
#PBS -P RDS-FEI-ForecastingSolar-RW
#PBS -l select=1:ncpus=12:mem=16gb:ngpus=1
#PBS -l walltime=05:00:00
#PBS -m abe
#PBS -M ylin4015@uni.sydney.edu.au

module load python/3.8.2 cuda/10.2.89 magma/2.5.3 gcc/7.4.0
source ~/pytorch/bin/activate 

cd "$PBS_O_WORKDIR"
python preprocess_elect.py --L=7 --H=1
python train.py --dataset='elect' --model-name='base_model_elect' --seed=1 > experiments/base_model_elect/results_elect.out
