#!/bin/bash
#PBS -P RDS-FEI-ForecastingSolar-RW
#PBS -l select=1:ncpus=12:mem=16gb:ngpus=1
#PBS -l walltime=00:05:00
#PBS -m abe
#PBS -M ylin4015@uni.sydney.edu.au

module load python/3.8.2 cuda/10.2.89 magma/2.5.3 gcc/7.4.0
source ~/pytorch/bin/activate 


cd "$PBS_O_WORKDIR"
#python preprocess_Sanyo.py --L=1 --H=1
#python train.py --dataset='Sanyo' --model-name='base_model_Sanyo' --restore-file='best'
#python preprocess_Sanyo.py --L=1 --H=5
#python train.py --dataset='Sanyo' --model-name='base_model_Sanyo_h5' --restore-file='best'
#python preprocess_Hanergy.py --L=1 --H=1
python train.py --dataset='Hanergy' --model-name='base_model_Hanergy'  --restore-file='best'
#python preprocess_Hanergy.py --L=1 --H=5
#python train.py --dataset='Hanergy' --model-name='base_model_Hanergy_h5' --restore-file='best'
#python preprocess_exchange.py --L=30 --H=20
#python train.py --dataset='exchange_rate' --model-name='base_model_exchange' --restore-file='best'
#python preprocess_exchange.py --L=30 --H=40
#python train.py --dataset='exchange_rate' --model-name='base_model_exchange_h40' --restore-file='best'
#python preprocess_exchange.py --L=30 --H=80
#python train.py --dataset='exchange_rate' --model-name='base_model_exchange_h80' --restore-file='best'
#python preprocess_solar.py --L=1 --H=1
#python train.py --dataset='Solar' --model-name='base_model_Solar' --restore-file='best'
#python preprocess_solar.py --L=1 --H=7
#python train.py --dataset='Solar' --model-name='base_model_Solar_h7'  --restore-file='best'
#python preprocess_elect.py --L=7 --H=1
#python train.py --dataset='elect' --model-name='base_model_elect' --restore-file='best'
#python preprocess_traffic.py --L=7 --H=1
#python train.py --dataset='traffic' --model-name='base_model_traffic' --restore-file='best'